services:
  - type: web
    name: kbo-prediction-api
    env: python
    plan: standard
    buildCommand: pip install --no-cache-dir -r python_server/requirements.txt
    startCommand: >
      cd python_server && 
      gunicorn 
        -w 2 
        -b 0.0.0.0:$PORT 
        --timeout 600 
        --access-logfile - 
        --error-logfile - 
        app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_DEFAULT_TIMEOUT
        value: 300
      - key: PYTHONUNBUFFERED
        value: true
